### ISSUE TITLE
trying to get this to work

### ISSUE THREAD

**Issue by michaeljcoyne** [langemike/laravel5-less#3]
I am not sure by the documentation what to do

I have tried this 

 Less::modifyVars(['@insight-yellow' => 'pink'])->recompile('admin-theme/less/variables.less');

nothing is generated.

What am I doing wrong?

**Comment by langemike** [comment]
No errors also? Thats weird.

You also need to provide a filename (without .less) as argument on the recompile method

**Comment by langemike** [comment]
And you need to setup your environment correcty with a public and less path set etc.

If you send me the whole path of your less file (starting from the root of your site) then i think i can help you

**Comment by michaeljcoyne** [comment]
laravel/resources/assets/less/admin-theme/less/variables.less is the path.

--config:
    'public_path' => public_path('css'),
    'link_path' => '/css',
    'less_path' => base_path('resources/assets/less'),
    'cache_dir' => storage_path('framework/cache/lessphp'
- not getting errors and nothing is generated.

**Comment by michaeljcoyne** [comment]
also you don't need to put this in composer do you?

 "require": {
        "oyejorge/less.php": "~1.5"
    }

**Comment by langemike** [comment]
The methods used in Less.php only support filenames. Not whole file paths. If you want to use file paths, please use @import rules provided in the LESS language itself.

To get it to work you should do something like this:
1. Create a new file "style.less" in resources/assets/less. 
2. Save it with the following: @import "admin-theme/less/variables.less";
3. Execute this in your code: Less::modifyVars(['@insight-yellow' => 'pink'])->recompile('style');

If you only have variables defined and you don't do anything with it, there is also nothing to compile.. So i would believe you get a blank file.

Maybe add the following at the bottom of style.less to get some output to your style.css file:
body {background-color: @insight-yellow; }

And you shouldn't need to add oyejorge/less.php to your composer.json since i have already added it to mine composer.json you should be fine :)

Please also make sure the recompile setting is setted to RECOMPILE_CHANGE or RECOMPILE_ALWAYS. Because if it's set on RECOMPILE_NONE it will obviously do nothing.

You can provide a second parameter to the recompile method to force the recompile setting. Something like this:
Less::modifyVars(['@insight-yellow' => 'pink'])->recompile('style', 'change');

**Comment by michaeljcoyne** [comment]
cool got it to work. Thanks.
